language: java
services:
  - xvfb
sudo: false
jdk:
- openjdk11
branches:
  only:
  - java11
install:
- cp .travis.settings.xml $HOME/.m2/settings.xml
script: mvn clean install -U -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

deploy:
  on:
    branch: java11
  provider: script
  script: "mvn deploy"
  skip_cleanup: true
