language: java
services:
  - xvfb
sudo: false
jdk:
- openjdk11
install:
- cp .travis.settings.xml $HOME/.m2/settings.xml

script: ""

deploy:
  provider: script
  on:
    branch: java11
  script: "mvn deploy"
  skip_cleanup: true
