language: java
services:
  - xvfb
sudo: false
jdk:
- openjdk11

deploy:
  provider: script
  on:
    branch: java11
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
