language: java
services:
  - xvfb
sudo: false
jdk:
- openjdk11
install:
- cp .travis.settings.xml $HOME/.m2/settings.xml

script: ""

deploy:
  provider: script
  on:
    branch: develop
  script: "mvn deploy -U -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
  skip_cleanup: true
