language: java
services:
  - xvfb
sudo: false
jdk:
- openjdk11
branches:
  only:
  - java11

deploy:
  on:
    branch: java11
  provider: script
  script: "- cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -U -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
  skip_cleanup: true
