package org.cytoscape.search.internal.ui;

import org.cytoscape.application.CyApplicationManager;
import org.cytoscape.model.CyNetwork;
import org.cytoscape.search.internal.EnhancedSearch;
import org.cytoscape.search.internal.SearchTaskFactory;
import org.cytoscape.view.model.CyNetworkViewManager;
import org.cytoscape.work.swing.DialogTaskManager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EnhancedSearchPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 3748296514173533886L;
	
	private static final Logger logger = LoggerFactory.getLogger(EnhancedSearchPanel.class);
	
	private CyApplicationManager appManager;
	private EnhancedSearch searchMgr;
	private DialogTaskManager taskMgr;
	
	private final CyNetworkViewManager viewManager;

	/** Creates new form NewJPanel */
	public EnhancedSearchPanel(CyApplicationManager appManager, final CyNetworkViewManager viewManager, EnhancedSearch searchMgr,
			DialogTaskManager taskMgr) {
		initComponents();

		// Turn off this for now, we may need this later
		this.btnSearch.setVisible(false);
		this.lbSearch.setVisible(true);

		this.appManager = appManager;
		this.searchMgr = searchMgr;
		this.taskMgr = taskMgr;
		this.viewManager = viewManager;
	}

	private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
		doSearching();
	}

	private void tfSearchTextActionPerformed(java.awt.event.ActionEvent evt) {
		doSearching();
	}

	// Do searching based on the query string from user on text-field
	private void doSearching() {
		final String queryStr = this.tfSearchText.getText().trim();
		logger.info("Search Start.  Query text = " + queryStr);

		final CyNetwork currentNetwork = appManager.getCurrentNetwork();
		if (currentNetwork != null) {
			logger.debug("Target Network ID = " + currentNetwork.getSUID());

			final SearchTaskFactory factory = new SearchTaskFactory(currentNetwork, searchMgr,
					queryStr, viewManager, appManager);
			this.taskMgr.execute(factory);
		} else
			logger.error("Could not find network for search");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// @SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		lbSearch = new javax.swing.JLabel();
		tfSearchText = new javax.swing.JTextField();
		btnSearch = new javax.swing.JButton();

		lbSearch.setText("Search:");
		lbSearch.setName("lbSearch"); // NOI18N
		add(lbSearch);

		tfSearchText.setToolTipText("Enter search text");
		tfSearchText.setName("tfSearchText"); // NOI18N
		tfSearchText.setPreferredSize(new java.awt.Dimension(150, 25));
		tfSearchText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tfSearchTextActionPerformed(evt);
			}
		});
		add(tfSearchText);

		btnSearch.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
		btnSearch.setText("Search");
		btnSearch.setName("btnSearch"); // NOI18N
		btnSearch.setPreferredSize(new java.awt.Dimension(70, 23));
		btnSearch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSearchActionPerformed(evt);
			}
		});
		add(btnSearch);
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JButton btnSearch;
	private javax.swing.JLabel lbSearch;
	private javax.swing.JTextField tfSearchText;
	// End of variables declaration
}
