package org.cytoscape.app.internal.ui;

import java.awt.Component;
import java.awt.Container;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.net.URISyntaxException;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkEvent.EventType;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.HyperlinkListener;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.text.html.HTMLDocument;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;

import org.cytoscape.app.internal.exception.AppDownloadException;
import org.cytoscape.app.internal.exception.AppInstallException;
import org.cytoscape.app.internal.exception.AppParsingException;
import org.cytoscape.app.internal.manager.App;
import org.cytoscape.app.internal.manager.AppManager;
import org.cytoscape.app.internal.manager.AppParser;
import org.cytoscape.app.internal.net.ResultsFilterer;
import org.cytoscape.app.internal.net.WebApp;
import org.cytoscape.app.internal.net.WebQuerier;
import org.cytoscape.app.internal.util.DebugHelper;
import org.cytoscape.util.swing.FileChooserFilter;
import org.cytoscape.util.swing.FileUtil;
import org.cytoscape.work.Task;
import org.cytoscape.work.TaskIterator;
import org.cytoscape.work.TaskManager;
import org.cytoscape.work.TaskMonitor;

/**
 * This class represents the panel in the App Manager dialog's tab used for installing new apps.
 * Its UI setup code is generated by the Netbeans 7 GUI builder.
 */
public class InstallFromStorePanel extends javax.swing.JPanel {
	
	/** Long serial version identifier required by the Serializable class */
	private static final long serialVersionUID = -1208176142084829272L;
	
	private javax.swing.JTextField filterTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTree jTree2;
    private javax.swing.JLabel searchAppsLabel;
	
	private JFileChooser fileChooser;
	
	private AppManager appManager;
	private FileUtil fileUtil;
	private TaskManager taskManager;
	private Container parent;
	
    public InstallFromStorePanel(final AppManager appManager, FileUtil fileUtil, TaskManager taskManager, Container parent) {
        this.appManager = appManager;
        this.fileUtil = fileUtil;
        this.taskManager = taskManager;
        this.parent = parent;
    	initComponents();
        
		taskManager.execute(new TaskIterator(new Task() {
			
			// Obtain information for all available apps, then append tag information
			@Override
			public void run(TaskMonitor taskMonitor) throws Exception {
				taskMonitor.setTitle("Obtaining Apps from App Store");
				
				WebQuerier webQuerier = appManager.getWebQuerier();
		    	
				taskMonitor.setStatusMessage("Getting available apps");
				Set<WebApp> availableApps = webQuerier.getAllApps();
				
				// Note: Code below not used because web store now returns tag information when
				// returning all apps
				
				/* 
		    	// Obtain available tags
		    	Set<WebQuerier.AppTag> availableTags = webQuerier.getAllTags();
		    	
		    	double progress = 0;
		    	
		    	for (WebQuerier.AppTag appTag : availableTags) {

		    		taskMonitor.setStatusMessage("Getting apps for tag: " + appTag.getFullName());
		    		progress += 1.0 / availableTags.size();
		    		taskMonitor.setProgress(progress);
		    		
		    		// Obtain apps for the current tag
		    		Set<WebApp> tagApps = webQuerier.getAppsByTag(appTag.getName());
		    		
		    		// Assume the set of apps returned is a subset of all available apps
		    		for (WebApp tagApp : tagApps) {
		    			tagApp.getAppTags().add(appTag);
		    		}
		    	}
				*/
				
				// Once the information is obtained, update the tree
				
				SwingUtilities.invokeLater(new Runnable() {

					@Override
					public void run() {
						// populateTree(appManager.getWebQuerier().getAllApps());
						buildTagsTree();
						
						jTree1.addTreeSelectionListener(new TreeSelectionListener() {
							
							@Override
							public void valueChanged(TreeSelectionEvent arg0) {
								updateResultsTree();
							}
						});
						
						jTree2.addTreeSelectionListener(new TreeSelectionListener() {
							
							@Override
							public void valueChanged(TreeSelectionEvent e) {
								updateDescriptionBox();
							}
						});
						
						
						// TODO: Set tree to be initially empty rather than use this call
						jTree2.setModel(new DefaultTreeModel(null));
					}
					
				});
				
			}

			@Override
			public void cancel() {
			}
			
		}));
    	
		/*
		addTagInformation();
        populateTree(appManager.getWebQuerier().getAllApps());
        */
		
		/*
        setupDescriptionListener();
        setupHyperlinkListener();
        setupTextFieldListener();
        */
		
		
    }

    private void initComponents() {

    	searchAppsLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        filterTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();

        searchAppsLabel.setText("Search:");

        jButton1.setText("Install from File...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        //jTextPane1.setText("App hyperlink\n\nApp icon\n\n\nApp name\n\nApp description");
        jTextPane1.setText("App information is displayed here.");
        
        jScrollPane3.setViewportView(jTextPane1);

        jButton4.setText("Install");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(jTree1);

        jScrollPane2.setViewportView(jTree2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(searchAppsLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(filterTextField)
                        .add(183, 183, 183))
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 182, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jButton1)
                        .add(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(searchAppsLabel)
                    .add(filterTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addContainerGap())
        );
    }

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }
    
    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	// Setup a the file filter for the open file dialog
    	FileChooserFilter fileChooserFilter = new FileChooserFilter("Jar, Zip Files (*.jar, *.zip)",
    			new String[]{"jar", "zip"});
    	
    	Collection<FileChooserFilter> fileChooserFilters = new LinkedList<FileChooserFilter>();
    	fileChooserFilters.add(fileChooserFilter);
    	
    	// Show the dialog
    	File[] files = fileUtil.getFiles(parent, 
    			"Choose file(s)", FileUtil.LOAD, FileUtil.LAST_DIRECTORY, "Install", true, fileChooserFilters);
    	
        if (files != null) {
        	
        	for (int index = 0; index < files.length; index++) {
        		AppParser appParser = appManager.getAppParser();
        		
        		App app = null;
        		
        		// Attempt to parse each file as an App object
        		try {
					app = appParser.parseApp(files[index]);
					
				} catch (AppParsingException e) {
					
					// TODO: Replace DebugHelper.print() messages with exception or a pop-up message box
					DebugHelper.print("Error parsing app: " + e.getMessage());
					
					JOptionPane.showMessageDialog(parent, "Error opening app: " + e.getMessage(),
		                       "Error", JOptionPane.ERROR_MESSAGE);
				} finally {
					
					// Install the app if parsing was successful
					if (app != null) {
						try {
							appManager.installApp(app);
						} catch (AppInstallException e) {
							JOptionPane.showMessageDialog(parent, "Error installing app: " + e.getMessage(),
				                       "Error", JOptionPane.ERROR_MESSAGE);
						}
					}
				}
        	}
        }
    }
    
    /**
     * Attempts to insert newlines into a given string such that each line has no 
     * more than the specified number of characters.
     */
    private String splitIntoLines(String text, int charsPerLine) {
    	return null;
    }

    private void setupTextFieldListener() {
        filterTextField.getDocument().addDocumentListener(new DocumentListener() {
			
			@Override
			public void removeUpdate(DocumentEvent arg0) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void insertUpdate(DocumentEvent arg0) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void changedUpdate(DocumentEvent arg0) {
				// TODO Auto-generated method stub
				
			}
		});
    }
    
    
    private void searchComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {

    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    private void buildTagsTree() {
    	WebQuerier webQuerier = appManager.getWebQuerier();
    	
    	// Obtain available tags
    	Set<WebQuerier.AppTag> availableTags = webQuerier.getAllTags();
    	
    	
    	
    	DefaultMutableTreeNode root = new DefaultMutableTreeNode("root");
    	
    	DefaultMutableTreeNode allAppsTreeNode = new DefaultMutableTreeNode("all apps" 
    			+ " (" + webQuerier.getAllApps().size() + ")");
    	root.add(allAppsTreeNode);
    	
    	DefaultMutableTreeNode appsByTagTreeNode = new DefaultMutableTreeNode("apps by tag");
    	root.add(appsByTagTreeNode);
    	
    	DefaultMutableTreeNode treeNode = null;
    	for (final WebQuerier.AppTag appTag : availableTags) {
    		if (appTag.getCount() > 0) {
    			treeNode = new DefaultMutableTreeNode(appTag);
    			appsByTagTreeNode.add(treeNode);
    		}
    	}
    	
    	jTree1.setModel(new DefaultTreeModel(root));
    	jTree1.expandRow(1);
    	jTree1.setRootVisible(false);
    }
 
    private void updateResultsTree() {
    	
    	DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();
    	
//    	DebugHelper.print(String.valueOf(selectedNode.getUserObject()));
    	
    	// Check if the "all apps" node is selected
    	if (selectedNode.getLevel() == 1 
    			&& String.valueOf(selectedNode.getUserObject()).startsWith("all apps")) {
    		fillResultsTree(null);
    		
    	} else if (selectedNode.getUserObject() instanceof WebQuerier.AppTag) {
    		WebQuerier.AppTag selectedTag = (WebQuerier.AppTag) selectedNode.getUserObject();
    		
    		fillResultsTree(selectedTag);
    	} else {
    		// Clear tree
    		jTree2.setModel(new DefaultTreeModel(null));
    	}
    }
    
    
    // Use appTag == null to show all apps
    private void fillResultsTree(WebQuerier.AppTag appTag) {
    	WebQuerier webQuerier = appManager.getWebQuerier();
    	Set<WebApp> appsToBeShown;
    	
    	if (appTag != null) {
    		appsToBeShown = webQuerier.getAppsByTag(appTag.getName());
    	} else {
    		appsToBeShown = webQuerier.getAllApps();
    	}
    	
    	// TODO: Consider sorting?
    	
    	DefaultMutableTreeNode root = new DefaultMutableTreeNode("root");
    	
    	DefaultMutableTreeNode treeNode;
    	for (WebApp webApp : appsToBeShown) {
    		treeNode = new DefaultMutableTreeNode(webApp);
    		root.add(treeNode);
    	}
    	
    	jTree2.setModel(new DefaultTreeModel(root));
    	jTree2.setRootVisible(false);
    }
    
    private void updateDescriptionBox() {
    	
    }

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void viewOnWebStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    /**
     * Populate the current tree of results with the available apps from the web store.
     */
    /*
    private void populateTreeOld() {
    	WebQuerier webQuerier = appManager.getWebQuerier();
    	
    	DefaultMutableTreeNode root = new DefaultMutableTreeNode("Available Apps (" + webQuerier.getAllApps().size() + ")");
    	
    	// Obtain available tags
    	Set<WebQuerier.AppTag> availableTags = webQuerier.getAllTags();
    	
    	for (WebQuerier.AppTag appTag : availableTags) {
    		DefaultMutableTreeNode tagNode = new DefaultMutableTreeNode(appTag.getFullName() + " (" + appTag.getCount() + ")");
    		
    		// Obtain apps for the current tag
    		DebugHelper.print("Getting apps for tag: " + appTag.getName());
    		Set<WebApp> tagApps = webQuerier.getAppsByTag(appTag.getName());
    		
    		for (WebApp tagApp : tagApps) {
    			tagNode.add(new DefaultMutableTreeNode(tagApp));
    		}
    		
    		root.add(tagNode);
    	}
    	
    	resultsTree.setModel(new DefaultTreeModel(root));
    }
    */
    
}
