package org.cytoscape.ding.impl.customgraphics.ui;

import java.awt.Image;
import java.util.Collection;

import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import org.cytoscape.application.CyApplicationManager;
import org.cytoscape.ding.customgraphics.CyCustomGraphics;
import org.cytoscape.ding.customgraphics.Taggable;
import org.cytoscape.ding.impl.customgraphics.bitmap.URLImageCustomGraphics;
import org.jdesktop.swingx.JXImageView;

/**
 * 
 */
public class CustomGraphicsDetailPanel extends JPanel implements
		ListSelectionListener {

	private static final long serialVersionUID = -412539582192509545L;

	private static final String TAG_DELIMITER = ",";
	
	private CyCustomGraphics cg;
	
	private final CyApplicationManager appManager;

	/** Creates new form CustomGraphicsDetailPanel */
	public CustomGraphicsDetailPanel(final CyApplicationManager appManager) {
		this.appManager = appManager;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		infoPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        tagLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        tagTextField = new javax.swing.JTextField();
        imageViewPanel = new JXImageView();
        modifyPanel = new javax.swing.JPanel();
        widthLabel = new javax.swing.JLabel();
        widthTextField = new javax.swing.JTextField();
        heightLabel = new javax.swing.JLabel();
        lockCheckBox = new javax.swing.JCheckBox();
        heightTextField = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();

        infoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameLabel.setText("Name:");

        tagLabel.setText("Tags:");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        tagTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagsTextFieldActionPerformed(evt);
            }
        });

        GroupLayout infoPanelLayout = new GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(tagLabel)
                    .addComponent(nameLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField, GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addComponent(tagTextField, GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
                .addContainerGap())
        );
        
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(tagLabel)
                    .addComponent(tagTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imageViewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Actual Size View"));

        GroupLayout imageViewPanelLayout = new GroupLayout(imageViewPanel);
        imageViewPanel.setLayout(imageViewPanelLayout);
        imageViewPanelLayout.setHorizontalGroup(
            imageViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );
        imageViewPanelLayout.setVerticalGroup(
            imageViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        modifyPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        widthLabel.setText("Width:");

        widthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                widthTextFieldActionPerformed(evt);
            }
        });

        heightLabel.setText("Height:");

        lockCheckBox.setSelected(true);
        lockCheckBox.setText("Aspect Ratio");
        lockCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //lockCheckBoxActionPerformed(evt);
            }
        });

        heightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTextFieldActionPerformed(evt);
            }
        });

        resetButton.setText("Original");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.setToolTipText("This function is not implemented yet.");
        searchButton.setEnabled(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionButtonActionPerformed(evt);
            }
        });

        GroupLayout modifyPanelLayout = new GroupLayout(modifyPanel);
        modifyPanel.setLayout(modifyPanelLayout);
        modifyPanelLayout.setHorizontalGroup(
            modifyPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(modifyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(widthLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(widthTextField, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(heightLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(heightTextField, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lockCheckBox)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchButton)
                .addGap(8, 8, 8))
        );
        modifyPanelLayout.setVerticalGroup(
            modifyPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(modifyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modifyPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(widthLabel)
                    .addComponent(widthTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightLabel)
                    .addComponent(heightTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lockCheckBox)
                    .addComponent(resetButton)
                    .addComponent(searchButton))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(infoPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(modifyPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) //TODO: is this correct layout?
            .addComponent(imageViewPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(infoPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageViewPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifyPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
	}// </editor-fold>

	private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
		final String newName = this.nameTextField.getText();
		if (newName != null && newName.trim().length() != 0 && cg != null)
			cg.setDisplayName(this.nameTextField.getText());
	}
	

	private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {
		if (cg == null || cg.getRenderedImage() == null)
			return;

		if (cg instanceof URLImageCustomGraphics) {
			final Image image = ((URLImageCustomGraphics) cg).resetImage();
			imageViewPanel.setImage(image);
			final int w = image.getWidth(null);
			final int h = image.getHeight(null);
			widthTextField.setText(Integer.toString(w));
			heightTextField.setText(Integer.toString(h));
			cg.setWidth(w);
			cg.setHeight(h);
			
			appManager.getCurrentNetworkView().updateView();
		}
	}

	private void widthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
		resizeImage(true);
	}

	private void heightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
		resizeImage(false);
	}

	private void resizeImage(boolean isWidth) {
		final String width = widthTextField.getText();
		final String height = heightTextField.getText();


		final Image currentImage = cg.getRenderedImage();
		if (currentImage == null)
			return;

		final boolean lock = this.lockCheckBox.isSelected();

		final int currentW = currentImage.getWidth(null);
		final int currentH = currentImage.getHeight(null);

		Integer w;
		Integer h;
		try {
			w = Integer.parseInt(width);
			h = Integer.parseInt(height);
		} catch (NumberFormatException e) {
			// back to current size
			this.widthTextField.setText(Integer.toString(currentW));
			this.heightTextField.setText(Integer.toString(currentH));
			return;
		}

		float ratio;
		int converted;
		if (lock == false) {
			cg.setWidth(w);
			cg.setHeight(h);
			imageViewPanel.setImage(cg.getRenderedImage());
		} else if (isWidth) {
			ratio = ((float) currentH) / ((float) currentW);
			converted = (int) (w * ratio);
			cg.setWidth(w);
			cg.setHeight(converted);
			imageViewPanel.setImage(cg.getRenderedImage());
			heightTextField.setText(Integer.toString(converted));
		} else {
			ratio = ((float) currentW) / ((float) currentH);
			converted = (int) (h * ratio);
			cg.setWidth(converted);
			cg.setHeight(h);
			imageViewPanel.setImage(cg.getRenderedImage());
			widthTextField.setText(Integer.toString(converted));
		}
		appManager.getCurrentNetworkView().updateView();
	}

	private void tagsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
		final String tagStr = this.tagTextField.getText();
		if(tagStr != null && tagStr.trim().length() != 0) {
			if(cg instanceof Taggable) {
				final String[] tags = tagStr.split(TAG_DELIMITER);
				for(String tag:tags)
					((Taggable) cg).getTags().add(tag.trim());
			}			
		}
	}
	
	private void optionButtonActionPerformed(java.awt.event.ActionEvent evt) {
    }
	
	

	// Variables declaration - do not modify
	private javax.swing.JLabel heightLabel;
	private javax.swing.JTextField heightTextField;
	private JXImageView imageViewPanel;
	private javax.swing.JPanel infoPanel;
	private javax.swing.JCheckBox lockCheckBox;
	private javax.swing.JPanel modifyPanel;
	private javax.swing.JLabel nameLabel;
	private javax.swing.JTextField nameTextField;
	private javax.swing.JButton resetButton;
	private javax.swing.JLabel tagLabel;
	private javax.swing.JTextField tagTextField;
	private javax.swing.JLabel widthLabel;
	private javax.swing.JTextField widthTextField;
    private javax.swing.JButton searchButton;


	// End of variables declaration

	public void valueChanged(ListSelectionEvent e) {

		if (!(e.getSource() instanceof CustomGraphicsBrowser)
				|| e.getValueIsAdjusting())
			return;

		final CustomGraphicsBrowser browser = (CustomGraphicsBrowser) e
				.getSource();

		cg = (CyCustomGraphics) browser.getSelectedValue();
		if(cg == null) {
			imageViewPanel.setImage((Image)null);
			heightTextField.setText(null);
			widthTextField.setText(null);
			nameTextField.setText(null);
			nameTextField.setToolTipText(null);
			tagTextField.setText(null);
			return;
		}
			
		final Image img = cg.getRenderedImage();

		// Set up detail panel
		imageViewPanel.setImage(img);
		heightTextField.setText(Integer.toString(img.getHeight(null)));
		widthTextField.setText(Integer.toString(img.getWidth(null)));
		nameTextField.setText(cg.getDisplayName());
		nameTextField.setToolTipText(cg.getDisplayName());
		if(cg instanceof Taggable) {
			final Collection<String> tags = ((Taggable) cg).getTags();
			final int tagCount = tags.size();
			int counter = 0;
			final StringBuilder tagBuilder = new StringBuilder();
			for(String tag: tags) {
				tagBuilder.append(tag);
				counter++;
				if(tagCount != counter)
					tagBuilder.append(", ");
			}
			tagTextField.setText(tagBuilder.toString());
			tagTextField.setToolTipText(tagBuilder.toString());
		}
	}

}
