/*
 Copyright (c) 2006, 2007, The Cytoscape Consortium (www.cytoscape.org)

 The Cytoscape Consortium is:
 - Institute for Systems Biology
 - University of California San Diego
 - Memorial Sloan-Kettering Cancer Center
 - Institut Pasteur
 - Agilent Technologies

 This library is free software; you can redistribute it and/or modify it
 under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation; either version 2.1 of the License, or
 any later version.

 This library is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY, WITHOUT EVEN THE IMPLIED WARRANTY OF
 MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  The software and
 documentation provided hereunder is on an "as is" basis, and the
 Institute for Systems Biology and the Whitehead Institute
 have no obligations to provide maintenance, support,
 updates, enhancements or modifications.  In no event shall the
 Institute for Systems Biology and the Whitehead Institute
 be liable to any party for direct, indirect, special,
 incidental or consequential damages, including lost profits, arising
 out of the use of this software and its documentation, even if the
 Institute for Systems Biology and the Whitehead Institute
 have been advised of the possibility of such damage.  See
 the GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this library; if not, write to the Free Software Foundation,
 Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
*/
package org.cytoscape.internal.dialogs;

import java.awt.Window;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.swing.GroupLayout;
import javax.swing.Icon;
import javax.swing.JEditorPane;
import javax.swing.LayoutStyle;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;

import org.cytoscape.util.swing.OpenBrowser;


/**
 * About page for web service clients or other plugins.
 * Accepts HTML as the argument.
 *
 * @author  kono
 */
class AboutDialogImpl extends javax.swing.JDialog implements HyperlinkListener {
	private final static long serialVersionUID = 1213748837120927L;

	private OpenBrowser openBrowser;
	// Show method with full parameter set.
	/**
	 *  DOCUMENT ME!
	 *
	 * @param title DOCUMENT ME!
	 * @param icon DOCUMENT ME!
	 * @param description DOCUMENT ME!
	 */
	public void showDialog(String title, Icon icon, String description) {
		titleLabel.setText(title);
		titleLabel.setIcon(icon);

		URL target = null;
        mainEditorPane.putClientProperty(JEditorPane.HONOR_DISPLAY_PROPERTIES,
                    Boolean.TRUE);
        try {
			target = new URL(description);
		} catch (MalformedURLException e) {
            mainEditorPane.setContentType("text/html");
			mainEditorPane.setText(description);
			repaint();
			setVisible(true);
			return;
		}

		try {
			mainEditorPane.setPage(target);
			pack();
			repaint();
			setVisible(true);
		} catch (IOException e) {
			mainEditorPane.setText("Could not connect to " + target.toString());
			e.printStackTrace();
			pack();
			repaint();
			setVisible(true);
		}
	}

	/** Creates new form WSAboutDialog */
	public AboutDialogImpl(Window parent, boolean modal, OpenBrowser ob) {
		// TODO: This is supported only in Java 6...
		//super(parent, modal);
		super();
		this.setModal(modal);
		this.openBrowser = ob;
		initComponents();
		mainEditorPane.setEditable(false);
		mainEditorPane.addHyperlinkListener(this);
		setLocationRelativeTo(parent);
		setAlwaysOnTop(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		titlePanel = new javax.swing.JPanel();
		titleLabel = new javax.swing.JLabel();
		mainPanel = new javax.swing.JPanel();
		mainScrollPane = new javax.swing.JScrollPane();
		mainEditorPane = new javax.swing.JEditorPane();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("About");
		setAlwaysOnTop(true);

		titlePanel.setBackground(new java.awt.Color(255, 255, 255));

		titleLabel.setFont(new java.awt.Font("SansSerif", 0, 18));
		titleLabel.setText("Client Name Here");

		GroupLayout titlePanelLayout = new GroupLayout(titlePanel);
		titlePanel.setLayout(titlePanelLayout);
		titlePanelLayout.setHorizontalGroup(titlePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
		                                                    .addGroup(titlePanelLayout.createSequentialGroup()
		                                                                         .addContainerGap()
		                                                                         .addComponent(titleLabel,
		                                                                              GroupLayout.DEFAULT_SIZE,
		                                                                              339,
		                                                                              Short.MAX_VALUE)
		                                                                         .addContainerGap()));
		titlePanelLayout.setVerticalGroup(titlePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
		                                                  .addGroup(titlePanelLayout.createSequentialGroup()
		                                                                       .addContainerGap()
		                                                                       .addComponent(titleLabel,
		                                                                            GroupLayout.DEFAULT_SIZE,
		                                                                            32,
		                                                                            Short.MAX_VALUE)
		                                                                       .addContainerGap()));

		mainPanel.setBackground(new java.awt.Color(255, 255, 255));

		mainScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		mainScrollPane.setFont(new java.awt.Font("SansSerif", 0, 12));

		mainEditorPane.setEditable(false);
		mainScrollPane.setViewportView(mainEditorPane);

		GroupLayout mainPanelLayout = new GroupLayout(mainPanel);
		mainPanel.setLayout(mainPanelLayout);
		mainPanelLayout.setHorizontalGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
		                                                  .addGroup(mainPanelLayout.createSequentialGroup()
		                                                                      .addContainerGap()
		                                                                      .addComponent(mainScrollPane)
		                                                                      .addContainerGap()));
		mainPanelLayout.setVerticalGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
		                                                .addGroup(mainPanelLayout.createSequentialGroup()
		                                                                    .addContainerGap()
		                                                                    .addComponent(mainScrollPane,
		                                                                         GroupLayout.DEFAULT_SIZE,
		                                                                         215,
		                                                                         Short.MAX_VALUE)
		                                                                    .addContainerGap()));

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
		                                .addComponent(titlePanel,
		                                     GroupLayout.DEFAULT_SIZE,
		                                     GroupLayout.DEFAULT_SIZE,
		                                     Short.MAX_VALUE)
		                                .addComponent(mainPanel,GroupLayout.Alignment.TRAILING,
		                                     GroupLayout.DEFAULT_SIZE,
		                                     GroupLayout.DEFAULT_SIZE,
		                                     Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
		                              .addGroup(layout.createSequentialGroup()
		                                         .addComponent(titlePanel,
		                                              GroupLayout.PREFERRED_SIZE,
		                                              GroupLayout.DEFAULT_SIZE,
		                                              GroupLayout.PREFERRED_SIZE)
		                                         .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		                                         .addComponent(mainPanel,
		                                              GroupLayout.DEFAULT_SIZE,
		                                              GroupLayout.DEFAULT_SIZE,
		                                              Short.MAX_VALUE)));

		pack();
	} // </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JEditorPane mainEditorPane;
	private javax.swing.JScrollPane mainScrollPane;
	private javax.swing.JLabel titleLabel;
	private javax.swing.JPanel titlePanel;
	private javax.swing.JPanel mainPanel;

	/**
	 *  DOCUMENT ME!
	 *
	 * @param e DOCUMENT ME!
	 */
	public void hyperlinkUpdate(HyperlinkEvent e) {
		if (e.getEventType() != HyperlinkEvent.EventType.ACTIVATED)
			return;

		String url = e.getURL().toString();

		try {
			openBrowser.openURL(url);
		} catch (Exception err) {
			err.printStackTrace();
		}
	}

	// End of variables declaration
}
