package org.cytoscape.task.internal.quickstart;

import java.util.List;
import javax.swing.JPanel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class MappingKeyTypePanel extends JPanel{

	/** Creates new form SelectMappingKeyTypePanel */
	public MappingKeyTypePanel(List<String> keyIDTypes, String[] tblHeader, String[][] tblData) {
		initComponents();
						
		DefaultComboBoxModel model = new DefaultComboBoxModel(keyIDTypes.toArray());
		cmbKeyIDTypes.setModel(model);
		
		DefaultTableModel tblModel = new DefaultTableModel(tblData, tblHeader);
		this.tblPreview.setModel(tblModel);
		this.tblPreview.setEnabled(false);
	}

	
	public String getSelectedValue(){
		return this.cmbKeyIDTypes.getSelectedItem().toString();
	}
	
	
	public String getOtherIDType()
	{
		return this.tfEnterIDType.getText().trim();
	}
	

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbSelectMappingKey = new javax.swing.JLabel();
        cmbKeyIDTypes = new javax.swing.JComboBox();
        lbEnterIDType = new javax.swing.JLabel();
        tfEnterIDType = new javax.swing.JTextField();
        pnlPreview = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPreview = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(23, 23));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(300, 300));
        setLayout(new java.awt.GridBagLayout());

        lbSelectMappingKey.setText("Select Mapping Key ID Type"); // NOI18N
        lbSelectMappingKey.setName("lbSelectMappingKey"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        add(lbSelectMappingKey, gridBagConstraints);

        cmbKeyIDTypes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmbKeyIDTypes.setName("cmbKeyIDTypes"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        //gridBagConstraints.ipadx = 5;
        //gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(cmbKeyIDTypes, gridBagConstraints);

        lbEnterIDType.setText("Or, Enter ID type"); // NOI18N
        lbEnterIDType.setName("lbEnterIDType"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lbEnterIDType, gridBagConstraints);

        tfEnterIDType.setName("tfEnterIDType"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        //gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(tfEnterIDType, gridBagConstraints);

        pnlPreview.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview"));
        //pnlPreview.setMinimumSize(new java.awt.Dimension(49, 47));
        pnlPreview.setName("pnlPreview"); // NOI18N
        pnlPreview.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblPreview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Key", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPreview.setName("tblPreview"); // NOI18N
        jScrollPane1.setViewportView(tblPreview);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlPreview.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        add(pnlPreview, gridBagConstraints);
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JComboBox cmbKeyIDTypes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEnterIDType;
    private javax.swing.JLabel lbSelectMappingKey;
    private javax.swing.JPanel pnlPreview;
    private javax.swing.JTable tblPreview;
    private javax.swing.JTextField tfEnterIDType;
    // End of variables declaration
	
}