package org.cytoscape.ding.impl.cyannotator.create;

public class cImageAnnotationPanel extends javax.swing.JPanel {

	/** Creates new form ImageAnnotation */
	public cImageAnnotationPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jFileChooser1 = new javax.swing.JFileChooser();

		setLayout(null);
		add(jFileChooser1);
		jFileChooser1.setBounds(0, 0, 465, 396);
	}// </editor-fold>//GEN-END:initComponents


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JFileChooser jFileChooser1;
	// End of variables declaration//GEN-END:variables

}
