
/*
 Copyright (c) 2006, 2007, The Cytoscape Consortium (www.cytoscape.org)

 The Cytoscape Consortium is:
 - Institute for Systems Biology
 - University of California San Diego
 - Memorial Sloan-Kettering Cancer Center
 - Institut Pasteur
 - Agilent Technologies

 This library is free software; you can redistribute it and/or modify it
 under the terms of the GNU Lesser General Public License as published
 by the Free Software Foundation; either version 2.1 of the License, or
 any later version.

 This library is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY, WITHOUT EVEN THE IMPLIED WARRANTY OF
 MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  The software and
 documentation provided hereunder is on an "as is" basis, and the
 Institute for Systems Biology and the Whitehead Institute
 have no obligations to provide maintenance, support,
 updates, enhancements or modifications.  In no event shall the
 Institute for Systems Biology and the Whitehead Institute
 be liable to any party for direct, indirect, special,
 incidental or consequential damages, including lost profits, arising
 out of the use of this software and its documentation, even if the
 Institute for Systems Biology and the Whitehead Institute
 have been advised of the possibility of such damage.  See
 the GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with this library; if not, write to the Free Software Foundation,
 Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
*/

package org.cytoscape.tableimport.internal.ui;

import org.cytoscape.tableimport.internal.util.AttributeTypes;
import static org.cytoscape.tableimport.internal.reader.TextFileDelimiters.*;

import java.awt.event.ActionEvent;

import javax.swing.DefaultComboBoxModel;

//import com.sun.xml.internal.bind.v2.schemagen.xmlschema.List;
import java.awt.Dialog;

/**
 *
 * @author kono
 */
public class AttributeTypeDialog extends javax.swing.JDialog {
	private static final String STRING = "List of Strings";
	private static final String INTEGER = "List of Integers";
	private static final String FLOAT = "List of Floating Point Numbers";
	private static final String BOOLEAN = "List of Booleans";
	private byte dataType;
	//private Byte dataType;
	private String name;
	private static final String[] LIST_DATA_TYPES = { STRING, INTEGER, FLOAT, BOOLEAN };

	/** Creates new form AttributeTypeDialog
	 * @param delimiter TODO*/
	public AttributeTypeDialog(Dialog parent, boolean modal, final String name, final byte dataType,
	                           int index, String delimiter) {
		super(parent, true);

		this.name = name;
		this.dataType = dataType;

		initComponents(index);
		updateComponents(delimiter);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc=" Generated Code">
	private void initComponents(int index) {
		delimiterButtonGroup = new javax.swing.ButtonGroup();
		listDelimiterButtonGroup = new javax.swing.ButtonGroup();

		titleLabel = new javax.swing.JLabel();
		titleSeparator = new javax.swing.JSeparator();
		attributeNameLabel = new javax.swing.JLabel();
		attributeNameTextField = new javax.swing.JTextField();
		cancelButton = new javax.swing.JButton();
		okButton = new javax.swing.JButton();
		dataTypePanel = new javax.swing.JPanel();
		stringRadioButton = new javax.swing.JRadioButton();
		integerRadioButton = new javax.swing.JRadioButton();
		floatingPointRadioButton = new javax.swing.JRadioButton();
		booleanRadioButton = new javax.swing.JRadioButton();
		listRadioButton = new javax.swing.JRadioButton();
		listTypeComboBox = new javax.swing.JComboBox();
		listDelimiterComboBox = new javax.swing.JComboBox();
		otherTextField = new javax.swing.JTextField();
		otherRadioButton = new javax.swing.JRadioButton();
		listDelimiterRadioButton = new javax.swing.JRadioButton();
		listDelimiterLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Set Attribute Name and Type");
		titleLabel.setFont(new java.awt.Font("SansSerif", 1, 14));
		titleLabel.setText("Attribute Name and Type");

		attributeNameLabel.setText("Attribute name for Column " + (index + 1) + " entry:");

		cancelButton.setText("Cancel");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					cancelButtonActionPerformed(evt);
				}
			});

		okButton.setText("OK");
		okButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					okButtonActionPerformed(evt);
				}
			});

		dataTypePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
		                                                                     "Attribute Data Type",
		                                                                     javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
		                                                                     javax.swing.border.TitledBorder.DEFAULT_POSITION,
		                                                                     new java.awt.Font("SansSerif",
		                                                                                       1, 11)));
		stringRadioButton.setText("String");
		stringRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		stringRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
		stringRadioButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					dataTypeRadioButtonActionPerformed(evt);
				}
			});

		integerRadioButton.setText("Integer");
		integerRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		integerRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
		integerRadioButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					dataTypeRadioButtonActionPerformed(evt);
				}
			});

		floatingPointRadioButton.setText("Floating Point");
		floatingPointRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		floatingPointRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
		floatingPointRadioButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					dataTypeRadioButtonActionPerformed(evt);
				}
			});

		booleanRadioButton.setText("Boolean");
		booleanRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		booleanRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
		booleanRadioButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					dataTypeRadioButtonActionPerformed(evt);
				}
			});

		listRadioButton.setText("List:");
		listRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		listRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
		listRadioButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					listRadioButtonActionPerformed(evt);
				}
			});

		listTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(LIST_DATA_TYPES));

		listDelimiterLabel.setText("List delimiter is:");

		listDelimiterComboBox.setModel(new DefaultComboBoxModel(new String[] {
		                                                                        "|",
		                                                                        COLON.toString(),
		                                                                        SLASH.toString(),
		                                                                        BACKSLASH.toString(),
		                                                                        COMMA.toString()
		                                                                    }));
		listDelimiterComboBox.setName("listDelimiterComboBox");

		otherRadioButton.setText("Other");
		otherRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		otherRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
		otherRadioButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					otherRadioButtonActionPerformed(evt);
				}
			});

		listDelimiterRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		listDelimiterRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
		listDelimiterRadioButton.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					listDelimiterRadioButtonActionPerformed(evt);
				}
			});
		listDelimiterRadioButton.setSelected(true);

		listDelimiterButtonGroup.add(listDelimiterRadioButton);
		listDelimiterButtonGroup.add(otherRadioButton);

		listDelimiterLabel.setText("List Delimiter is:");

		org.jdesktop.layout.GroupLayout dataTypePanelLayout = new org.jdesktop.layout.GroupLayout(dataTypePanel);
		dataTypePanel.setLayout(dataTypePanelLayout);

		dataTypePanelLayout.setHorizontalGroup(dataTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                                          .add(dataTypePanelLayout.createSequentialGroup()
		                                                                                  .addContainerGap()
		                                                                                  .add(dataTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                                                                                          .add(dataTypePanelLayout.createSequentialGroup()
		                                                                                                                                  .add(stringRadioButton)
		                                                                                                                                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                                                                                  .add(integerRadioButton)
		                                                                                                                                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                                                                                  .add(floatingPointRadioButton)
		                                                                                                                                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                                                                                  .add(booleanRadioButton))
		                                                                                                          .add(dataTypePanelLayout.createSequentialGroup()
		                                                                                                                                  .add(listRadioButton)
		                                                                                                                                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                                                                                  .add(dataTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                                                                                                                                          .add(listTypeComboBox,
		                                                                                                                                                               0,
		                                                                                                                                                               328,
		                                                                                                                                                               Short.MAX_VALUE)
		                                                                                                                                                          .add(dataTypePanelLayout.createSequentialGroup()
		                                                                                                                                                                                  .add(listDelimiterLabel)
		                                                                                                                                                                                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                                                                                                                                  .add(dataTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                                                                                                                                                                                          .add(dataTypePanelLayout.createSequentialGroup()
		                                                                                                                                                                                                                                  .add(otherRadioButton)
		                                                                                                                                                                                                                                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                                                                                                                                                                                  .add(otherTextField,
		                                                                                                                                                                                                                                       org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                                                                                                                                                                       155,
		                                                                                                                                                                                                                                       Short.MAX_VALUE))
		                                                                                                                                                                                                          .add(dataTypePanelLayout.createSequentialGroup()
		                                                                                                                                                                                                                                  .add(listDelimiterRadioButton)
		                                                                                                                                                                                                                                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                                                                                                                                                                                  .add(listDelimiterComboBox,
		                                                                                                                                                                                                                                       0,
		                                                                                                                                                                                                                                       194,
		                                                                                                                                                                                                                                       Short.MAX_VALUE)))))))
		                                                                                  .addContainerGap()));
		dataTypePanelLayout.setVerticalGroup(dataTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                                        .add(dataTypePanelLayout.createSequentialGroup()
		                                                                                .add(dataTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
		                                                                                                        .add(stringRadioButton)
		                                                                                                        .add(integerRadioButton)
		                                                                                                        .add(floatingPointRadioButton)
		                                                                                                        .add(booleanRadioButton))
		                                                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                                .add(dataTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
		                                                                                                        .add(listRadioButton)
		                                                                                                        .add(listTypeComboBox,
		                                                                                                             org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
		                                                                                                             org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                                             org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
		                                                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                                .add(dataTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                                                                                        .add(dataTypePanelLayout.createSequentialGroup()
		                                                                                                                                .add(30,
		                                                                                                                                     30,
		                                                                                                                                     30)
		                                                                                                                                .add(dataTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
		                                                                                                                                                        .add(otherRadioButton)
		                                                                                                                                                        .add(otherTextField,
		                                                                                                                                                             org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
		                                                                                                                                                             org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                                                                                             org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
		                                                                                                        .add(dataTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
		                                                                                                                                .add(listDelimiterLabel)
		                                                                                                                                .add(listDelimiterRadioButton)
		                                                                                                                                .add(listDelimiterComboBox,
		                                                                                                                                     org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
		                                                                                                                                     org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                                                                     org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
		                                                                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                                 Short.MAX_VALUE)));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                .add(layout.createSequentialGroup().addContainerGap()
		                                           .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                                      .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                                                 .add(layout.createSequentialGroup()
		                                                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                                                                                       .add(titleSeparator,
		                                                                                            org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                            340,
		                                                                                            Short.MAX_VALUE)
		                                                                                       .add(titleLabel)
		                                                                                       .add(attributeNameLabel))
		                                                                            .addContainerGap())
		                                                                 .add(layout.createSequentialGroup()
		                                                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
		                                                                                       .add(org.jdesktop.layout.GroupLayout.LEADING,
		                                                                                            dataTypePanel,
		                                                                                            org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                            org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                            Short.MAX_VALUE)
		                                                                                       .add(org.jdesktop.layout.GroupLayout.LEADING,
		                                                                                            attributeNameTextField,
		                                                                                            org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                                                            340,
		                                                                                            Short.MAX_VALUE))
		                                                                            .addContainerGap()))
		                                                      .add(org.jdesktop.layout.GroupLayout.TRAILING,
		                                                           layout.createSequentialGroup()
		                                                                 .add(okButton)
		                                                                 .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                                                 .add(cancelButton)
		                                                                 .addContainerGap()))));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
		                              .add(layout.createSequentialGroup().addContainerGap()
		                                         .add(titleLabel)
		                                         .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                         .add(titleSeparator,
		                                              org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
		                                              10,
		                                              org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
		                                         .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                         .add(attributeNameLabel)
		                                         .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                         .add(attributeNameTextField,
		                                              org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
		                                              org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                              org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
		                                         .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                         .add(dataTypePanel,
		                                              org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
		                                              org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                              org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
		                                         .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
		                                         .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
		                                                    .add(cancelButton).add(okButton))
		                                         .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
		                                                          Short.MAX_VALUE)));
		pack();
	} // </editor-fold>

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
		name = null;
		dispose();
	}

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
		name = attributeNameTextField.getText();
		dispose();
	}

	private void listRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
		if (listRadioButton.isSelected()) {
			if (otherRadioButton.isSelected()) {
				otherTextField.setEnabled(true);
			} else {
				listDelimiterComboBox.setEnabled(true);
				listTypeComboBox.setEnabled(true);
			}

			listDelimiterRadioButton.setEnabled(true);
			otherRadioButton.setEnabled(true);
		}
	}

	private void dataTypeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
		listDelimiterComboBox.setEnabled(false);
		listTypeComboBox.setEnabled(false);
		otherTextField.setEnabled(false);
		listDelimiterRadioButton.setEnabled(false);
		otherRadioButton.setEnabled(false);
	}

	private void otherRadioButtonActionPerformed(ActionEvent evt) {
		if (otherRadioButton.isSelected()) {
			otherTextField.setEnabled(true);
			listDelimiterComboBox.setEnabled(false);
		}
	}

	private void listDelimiterRadioButtonActionPerformed(ActionEvent evt) {
		if (listDelimiterRadioButton.isSelected()) {
			listDelimiterComboBox.setEnabled(true);
			otherTextField.setEnabled(false);
		}
	}

	/* =========================================================================================== */
	private void updateComponents(String delimiter) {
		attributeNameTextField.setText(name);
		listDelimiterComboBox.setEnabled(false);

		if (delimiter == null) {
			listDelimiterComboBox.setSelectedIndex(0);
		} else {
			for (int i = 0; i < listDelimiterComboBox.getItemCount(); i++) {
				if (delimiter.equals(listDelimiterComboBox.getItemAt(i))) {
					listDelimiterComboBox.setSelectedIndex(i);

					break;
				}
			}
		}

		listTypeComboBox.setEnabled(false);
		otherTextField.setEnabled(false);
		setButtonGroup();
	}

	private void setButtonGroup() {
		delimiterButtonGroup.add(stringRadioButton);
		delimiterButtonGroup.add(integerRadioButton);
		delimiterButtonGroup.add(floatingPointRadioButton);
		delimiterButtonGroup.add(booleanRadioButton);
		delimiterButtonGroup.add(listRadioButton);

		if (dataType == AttributeTypes.TYPE_STRING) {
			delimiterButtonGroup.setSelected(stringRadioButton.getModel(), true);
		} else if (dataType == AttributeTypes.TYPE_INTEGER) {
			delimiterButtonGroup.setSelected(integerRadioButton.getModel(), true);
		} else if (dataType == AttributeTypes.TYPE_FLOATING) {
			delimiterButtonGroup.setSelected(floatingPointRadioButton.getModel(), true);
		} else if (dataType == AttributeTypes.TYPE_BOOLEAN) {
			delimiterButtonGroup.setSelected(booleanRadioButton.getModel(), true);
		} else if (dataType == AttributeTypes.TYPE_SIMPLE_LIST) {
			delimiterButtonGroup.setSelected(listRadioButton.getModel(), true);
			listDelimiterComboBox.setEnabled(true);
			listTypeComboBox.setEnabled(true);
			otherTextField.setEnabled(false);
		}
	}

	/**
	 *  DOCUMENT ME!
	 *
	 * @return  DOCUMENT ME!
	 */
	public String getName() {
		return name;
	}

	/**
	 *  DOCUMENT ME!
	 *
	 * @return  DOCUMENT ME!
	 */
	byte getAttributeType() {
		if (delimiterButtonGroup.getSelection().equals(stringRadioButton.getModel())) {
			return AttributeTypes.TYPE_STRING;
		} else if (delimiterButtonGroup.getSelection().equals(integerRadioButton.getModel())) {
			return AttributeTypes.TYPE_INTEGER;
		} else if (delimiterButtonGroup.getSelection().equals(floatingPointRadioButton.getModel())) {
			return AttributeTypes.TYPE_FLOATING;
		} else if (delimiterButtonGroup.getSelection().equals(booleanRadioButton.getModel())) {
			return AttributeTypes.TYPE_BOOLEAN;
		} else if (delimiterButtonGroup.getSelection().equals(listRadioButton.getModel())) {
			return AttributeTypes.TYPE_SIMPLE_LIST;
		}

		return AttributeTypes.TYPE_STRING;
	}

	/**
	 *  DOCUMENT ME!
	 *
	 * @return  DOCUMENT ME!
	 */
	public String getListDelimiterType() {
		if (listDelimiterRadioButton.isSelected()) {
			if(listDelimiterComboBox.getSelectedItem().toString().equals("|")) {
				return PIPE.toString();
			} else
				return listDelimiterComboBox.getSelectedItem().toString();
		} else {
			return otherTextField.getText().trim();
		}
	}

	/**
	 * Returns data type of the entries in the list object.
	 * Complex type is not supported.
	 *
	 * @return
	 */
	public byte getListDataType() {
		if (listTypeComboBox.getSelectedItem().equals(STRING)) {
			return AttributeTypes.TYPE_STRING;
		} else if (listTypeComboBox.getSelectedItem().equals(INTEGER)) {
			return AttributeTypes.TYPE_INTEGER;
		} else if (listTypeComboBox.getSelectedItem().equals(FLOAT)) {
			return AttributeTypes.TYPE_FLOATING;
		} else if (listTypeComboBox.getSelectedItem().equals(BOOLEAN)) {
			return AttributeTypes.TYPE_BOOLEAN;
		}

		return AttributeTypes.TYPE_STRING;
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel attributeNameLabel;
	private javax.swing.JTextField attributeNameTextField;
	private javax.swing.JRadioButton booleanRadioButton;
	private javax.swing.JButton cancelButton;
	private javax.swing.JPanel dataTypePanel;
	private javax.swing.ButtonGroup delimiterButtonGroup;
	private javax.swing.JRadioButton floatingPointRadioButton;
	private javax.swing.JRadioButton integerRadioButton;
	private javax.swing.JComboBox listDelimiterComboBox;
	private javax.swing.JLabel listDelimiterLabel;
	private javax.swing.JRadioButton listDelimiterRadioButton;
	private javax.swing.JRadioButton listRadioButton;
	private javax.swing.JComboBox listTypeComboBox;
	private javax.swing.JButton okButton;
	private javax.swing.JRadioButton otherRadioButton;
	private javax.swing.JTextField otherTextField;
	private javax.swing.JRadioButton stringRadioButton;
	private javax.swing.JLabel titleLabel;
	private javax.swing.JSeparator titleSeparator;
	private javax.swing.ButtonGroup listDelimiterButtonGroup;

	// End of variables declaration
}
