package org.cytoscape.view.vizmap.gui.internal.editor.mappingeditor;

/*
 * #%L
 * Cytoscape VizMap GUI Impl (vizmap-gui-impl)
 * $Id:$
 * $HeadURL:$
 * %%
 * Copyright (C) 2006 - 2013 The Cytoscape Consortium
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as 
 * published by the Free Software Foundation, either version 2.1 of the 
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU General Lesser Public 
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * #L%
 */

import java.awt.Component;

import javax.swing.GroupLayout;
import javax.swing.JDialog;
import javax.swing.LayoutStyle;

/**
 * 
 * @author kono
 */
public class MinMaxDialog extends JDialog {
	private final static long serialVersionUID = 1213748836709924L;
	private static MinMaxDialog dialog;

	/** Creates new form MinMaxDialog */
	public MinMaxDialog(Component parent, boolean modal, Double min, Double max) {
		super();
		this.setModal(modal);
		this.setLocationRelativeTo(parent);
		this.min = min;
		this.max = max;
		initComponents();

		this.minTextField.setText(min.toString());
		this.maxTextField.setText(max.toString());
	}

	private Double min;
	private Double max;

	/**
	 * DOCUMENT ME!
	 * 
	 * @param min
	 *            DOCUMENT ME!
	 * @param max
	 *            DOCUMENT ME!
	 * 
	 * @return DOCUMENT ME!
	 */
	public static Double[] getMinMax(double min, double max, Component parent) {
		Double[] minMax = new Double[2];
		dialog = new MinMaxDialog(parent, true, min, max);
		dialog.setLocationRelativeTo(parent);
		dialog.setVisible(true);

		if ((dialog.min == null) || (dialog.max == null))
			return null;

		minMax[0] = dialog.min;
		minMax[1] = dialog.max;

		return minMax;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		minLabel = new javax.swing.JLabel();
		maxLabel = new javax.swing.JLabel();
		minTextField = new javax.swing.JTextField();
		maxTextField = new javax.swing.JTextField();
		okButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();
		titlePanel = new javax.swing.JPanel();
		titleLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Set Range");
		setModalityType(DEFAULT_MODALITY_TYPE);
		setResizable(false);

		minLabel.setFont(new java.awt.Font("SansSerif", 1, 12));
		minLabel.setText("Min");

		maxLabel.setFont(new java.awt.Font("SansSerif", 1, 12));
		maxLabel.setText("Max");

		okButton.setText("OK");
		okButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
		okButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okButtonActionPerformed(evt);
			}
		});

		cancelButton.setText("Cancel");
		cancelButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});

		titlePanel.setBackground(new java.awt.Color(255, 255, 255));

		titleLabel.setFont(new java.awt.Font("SansSerif", 1, 14));
		titleLabel.setText("Set Value Range");

		GroupLayout titlePanelLayout = new GroupLayout(titlePanel);
		titlePanel.setLayout(titlePanelLayout);
		titlePanelLayout.setHorizontalGroup(titlePanelLayout
				.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
						titlePanelLayout.createSequentialGroup()
								.addContainerGap().addComponent(titleLabel)
								.addContainerGap(125, Short.MAX_VALUE)));
		titlePanelLayout.setVerticalGroup(titlePanelLayout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addGroup(
				titlePanelLayout.createSequentialGroup().addContainerGap()
						.addComponent(titleLabel).addContainerGap(
								GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addComponent(titlePanel,
				GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
				Short.MAX_VALUE).addGroup(
				layout.createSequentialGroup().addContainerGap().addGroup(
						layout.createParallelGroup(
								GroupLayout.Alignment.LEADING).addComponent(
								minLabel, GroupLayout.PREFERRED_SIZE, 35,
								GroupLayout.PREFERRED_SIZE).addComponent(
								maxLabel, GroupLayout.DEFAULT_SIZE, 35,
								Short.MAX_VALUE)).addPreferredGap(
						LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								layout.createParallelGroup(
										GroupLayout.Alignment.LEADING)
										.addComponent(minTextField,
												GroupLayout.DEFAULT_SIZE, 182,
												Short.MAX_VALUE).addComponent(
												maxTextField,
												GroupLayout.DEFAULT_SIZE, 182,
												Short.MAX_VALUE))
						.addContainerGap())
				.addGroup(
						GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(163,
								Short.MAX_VALUE).addComponent(cancelButton)
								.addPreferredGap(
										LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(okButton).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(titlePanel,
						GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
						GroupLayout.PREFERRED_SIZE).addPreferredGap(
						LayoutStyle.ComponentPlacement.RELATED).addGroup(
						layout.createParallelGroup(
								GroupLayout.Alignment.BASELINE).addComponent(
								minLabel).addComponent(minTextField,
								GroupLayout.PREFERRED_SIZE, 18,
								GroupLayout.PREFERRED_SIZE)).addPreferredGap(
						LayoutStyle.ComponentPlacement.RELATED).addGroup(
						layout.createParallelGroup(
								GroupLayout.Alignment.BASELINE).addComponent(
								maxLabel).addComponent(maxTextField,
								GroupLayout.PREFERRED_SIZE, 18,
								GroupLayout.PREFERRED_SIZE)).addPreferredGap(
						LayoutStyle.ComponentPlacement.RELATED).addGroup(
						layout.createParallelGroup(
								GroupLayout.Alignment.BASELINE).addComponent(
								okButton).addComponent(cancelButton))
						.addContainerGap(GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		pack();
	} // </editor-fold>

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			min = Double.valueOf(minTextField.getText());
			max = Double.valueOf(maxTextField.getText());
		} catch (NumberFormatException e) {
			min = null;
			max = null;
		}

		dispose();
	}

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
		min = null;
		max = null;
		dispose();
	}

	// Variables declaration - do not modify
	private javax.swing.JButton cancelButton;
	private javax.swing.JLabel maxLabel;
	private javax.swing.JTextField maxTextField;
	private javax.swing.JLabel minLabel;
	private javax.swing.JTextField minTextField;
	private javax.swing.JButton okButton;
	private javax.swing.JLabel titleLabel;
	private javax.swing.JPanel titlePanel;

	// End of variables declaration
}
